add_executable(template_example template.cc)
target_link_libraries(template_example PRIVATE xcmixin)
add_executable(oop_example oop.cc)
target_link_libraries(oop_example PRIVATE xcmixin)
add_executable(overload_example overload-msvc-bug.cc)
target_link_libraries(overload_example PRIVATE xcmixin)
add_executable(threadsafe_example threadsafe.cc)
target_link_libraries(threadsafe_example PRIVATE xcmixin)
add_executable(decorator_example decorator.cc)
target_link_libraries(decorator_example PRIVATE xcmixin)
add_executable(composition_example composition.cc)
target_link_libraries(composition_example PRIVATE xcmixin)
